### ISSUE TITLE
Cannot Login after Registering with "password is too short"

### ISSUE THREAD

**Issue by Hempflingclub** [002Hub/IPost#41] opened 2022-10-22 05:23 UTC
After Registering with a Passwordlength < 10, I reRegistered with the same Username with a Password of the required Length

Afterwards when Logging in with longer Password, the URL shows: ?success=false&reason=already_exists, whilst logging in with the short Password returns "password is too short"

**Comment by Mystikfluu** [comment] 2022-10-22 05:41
if an account is already registered with a given username, the same username cannot be used again (until it is free)

#### please make sure you were on "/login", not "/register" as this may have been the issue.
if that wasn't the cause of the issue, then I currently can't replicate it, so I'd need more detailed steps

**Comment by Hempflingclub** [comment] 2022-10-22 18:45
Here is a demonstration of the Bug, I also failed to reproduce it with a new account

https://user-images.githubusercontent.com/29497373/197357529-b27ec584-6c25-4087-9202-2d59cf488264.mp4

**Comment by Mystikfluu** [comment] 2022-10-22 19:01
after digging through the logs and the database a bit, I found that the login simply failed (due to the password being incorrect)

if it is really your account and you simply forgot your password, then create a new account and mail [ipost-at-duck.com](mailto:ipost@duck.com) (with the other account name) , where I'll check the registration IP hashes and reset the account for you

I'll close this issue for now, if it really is a bug then it can always be reopened.

**Closed by Mystikfluu** 2022-10-22 19:01 UTC
Labels: question

**Comment by Hempflingclub** [comment] 2022-10-22 19:52
I recommend to change the `reason=noUser` feedback, as it was missleading enough to think the Issue was not because of User Inputs, especially not regarding the Password. I'd recommend changing to `invalid input` or `login error`
